# Generated by Django 3.1.2 on 2020-10-10 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('core', '0003_pontosturisticos_avaliacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='enderecos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enderecos.endereco'),
            preserve_default=False,
        ),
    ]
