# Generated by Django 3.1.2 on 2020-10-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('enderecos', '0001_initial'),
        ('atracoes', '0001_initial'),
        ('comentarios', '0001_initial'),
        ('core', '0004_pontosturisticos_enderecos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PontosTuristicos',
            new_name='PontoTuristico',
        ),
    ]
