# Generated by Django 3.1.2 on 2020-10-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pontoturistico_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='comentario',
            new_name='comentarios',
        ),
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='enderecos',
            new_name='endereco',
        ),
    ]
